version: '3.3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3306:3306
      - 8000:8000
    volumes:
      - $PWD:/app
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=projectdb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user123
      - TZ=America/Sao_Paulo
      - DEBIAN_FRONTEND=noninteractive