version: '3.8'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=projectdb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user123

volumes:
  db_data:
