# Generated by Django 3.2.12 on 2023-05-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('faculdade', models.CharField(max_length=100, verbose_name='Faculdade')),
                ('polo', models.CharField(max_length=100, verbose_name='Polo')),
            ],
        ),
    ]
