# Generated by Django 3.2.12 on 2023-05-29 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagehtml', '0002_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='nome',
        ),
    ]
